### ISSUE TITLE
IP_GETTER fails on Windows if using https

### ISSUE THREAD

**Issue by feikname** [piqueserver/piqueserver#215] opened 2017-12-25 00:04 UTC

**Comment by NotAFile** [comment] 2017-12-25 01:09
This is caused by lack of Twisted support for certificate validation on Windows.

https://twistedmatrix.com/trac/ticket/9209#ticket

Temporary workaround would be to make it use http if on windows instead

**Comment by swalladge** [comment] 2017-12-25 01:34
Can we simply make `IP_GETTER` configurable from the `config.json`? This would solve both this and the issue where `services.buildandshootcom` is down/inaccessible

**Comment by swalladge** [comment] 2017-12-25 01:35
(or even a list in the config so it can iterate through until one works)

**Comment by NotAFile** [comment] 2019-04-03 21:43
I'm going to close this since I assume this was fixed by the aiohttp switch.

**Closed by NotAFile** 2019-04-03 21:43 UTC
Labels: bug, waiting uptream
