### ISSUE TITLE
Bug when run the server

### ISSUE THREAD

**Issue by DeletedUser92** [piqueserver/piqueserver#598] opened 2020-07-07 18:44 UTC
We run "piqueserver" to start the server and we get this error: 
![Dale](https://media.discordapp.net/attachments/616476382377148426/730111050455973948/unknown.png)

Error: https://hatebin.com/obkksdsear

**Server (please complete the following information):**
 - OS/Version: Windows 8.1
 - Piqueserver Version: 1.0.0
 - Installation Method: pip (and we tested with git, and we get the same error)

**Comment by NotAFile** [comment] 2020-07-09 12:52
This is caused by newer versions of python defaulting to a different event loop which does not support the file readers we need. It should be fixed in `master` too.

**Comment by natan5388** [comment] 2020-07-10 01:14
that print is from my computer any guy tell me how to fix it in ``run.py`` 
Place {/AppData/Local/Programs/Python/Python38/lib/site-packages/piqueserver-1.0.0-py3.8-win-amd64.egg/piqueserver/run.py}
and put an # at start of line 248 now worked fine

**Closed** 2020-12-21 12:29 UTC
Labels: bug, triage
