### ISSUE TITLE
saving bans takes too long

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#455] opened 2019-02-03 17:11 UTC
Saving the aloha babel banlist takes 140ms, which is long enough that we start skipping ticks.

**Comment by swalladge** [comment] 2019-05-21 02:10
Can we close this as a duplicate of #158 ?

**Comment by swalladge** [comment] 2019-05-29 05:10
What's the order of magnitude of Aloha's banlist?

**Comment by NotAFile** [comment] 2019-05-29 17:02
20k for babel

**Closed** 2021-09-02 10:18 UTC
Labels: enhancement
