### ISSUE TITLE
Errors when trying to run after installing

### ISSUE THREAD

**Issue by pielover88888** [piqueserver/piqueserver#558] opened 2019-12-04 04:22 UTC
[link to a gist of the errors](https://gist.github.com/pielover88888/0dfbb4171a946d2d6e7e2ea9ad017d22) from running `python -m piqueserver -c config\config.toml` 

VS 2015 with Python 3.8, on Windows 7 (yes, I know, but I also used XP until 2012)

**Comment by NotAFile** [comment] 2019-12-04 04:24
Afaict, it looks like this means twisted doesn't suppprt asyncioreactor on windows.

**Comment by NotAFile** [comment] 2019-12-04 04:33
Looks like the solution might be to set the default asyncio event loop for windows to the SelectorEventLoop instead of the ProactorEventLoop. The ProactorEventLoop does not support several features that twisted appears to use.

**Comment by NotAFile** [comment] 2019-12-04 04:56
Issue is confirmed to be caused by the switch from SelectorEventLoop to ProactorEventLoop in python 3.8. Fixed by changing the event loop policy on windows.

**Closed** 2019-12-06 20:44 UTC
Labels: bug, priority:high
