### ISSUE TITLE
prevent people to crash/attack/ddos server?

### ISSUE THREAD

**Issue by MikkelDK** [piqueserver/piqueserver#372] opened 2018-09-03 11:27 UTC
Hello.

is it possible for prevent/anti for crash/attack the server for kill it down?

**Comment by NotAFile** [comment] 2018-09-03 13:02
duplicate of #366 

> you should be running piqueserver with a process supervisor like systemd, supervisord, daemontools, dockerd etc. That way if a crash occurs, the server will be instantly restarted.
> 
> We can't just "stop it from crashing". Any more than you can stop a car from crashing. If something goes wrong, it goes wrong.
> 
> Please make sure to report any specific crashes (with traceback) here so that we can fix them.

**Closed by NotAFile** 2018-09-03 13:02 UTC
