### ISSUE TITLE
Can't join spectator

### ISSUE THREAD

**Issue by xtreme8000** [piqueserver/piqueserver#382] opened 2018-10-22 21:41 UTC
It breaks at [player.py#L183](https://github.com/piqueserver/piqueserver/blob/master/pyspades/player.py#L183) because of an `int ↔️ byte` binary mismatch.
Team id for spectator is defined as `(byte)-1` in the protocol which is `255` as an int, so `255` is used to index the dict instead of `-1`.

The team id should be changed to 255 [here](https://github.com/piqueserver/piqueserver/blob/master/pyspades/server.py#L88) and [here](https://github.com/piqueserver/piqueserver/blob/master/pyspades/server.py#L95), or an additonal exception should be added when reading the packet(s).

*confirmed on Voxlap and BetterSpades*

full error:
```python
 Traceback (most recent call last):
   File "/home/piqueserver/venv/lib/python3.5/site-packages/piqueserver-0.1.3-py3.5-linux-armv7l.egg/pyspades/protocol.py", line 166, in update
     self.data_received(peer, event.packet)
   File "/home/piqueserver/venv/lib/python3.5/site-packages/piqueserver-0.1.3-py3.5-linux-armv7l.egg/piqueserver/server.py", line 755, in data_received
     ServerProtocol.data_received(self, peer, packet)
   File "/home/piqueserver/venv/lib/python3.5/site-packages/piqueserver-0.1.3-py3.5-linux-armv7l.egg/pyspades/protocol.py", line 118, in data_received
     connection.loader_received(packet)
   File "/home/piqueserver/venv/lib/python3.5/site-packages/piqueserver-0.1.3-py3.5-linux-armv7l.egg/pyspades/player.py", line 168, in loader_received
     call_packet_handler(self, loader)
   File "pyspades/packet.pyx", line 132, in pyspades.packet.call_packet_handler
     handler(self, contained)
   File "/home/piqueserver/venv/lib/python3.5/site-packages/piqueserver-0.1.3-py3.5-linux-armv7l.egg/pyspades/player.py", line 183, in on_new_player_recieved
     team = self.protocol.teams[contained.team]
 KeyError: 255
```

**Comment by NotAFile** [comment] 2018-10-22 22:15
Can't reproduce with current master

**Comment by NotAFile** [comment] 2018-10-23 14:49
It turns out on the target system, chars were unsigned by default. This is easily fixed by using stdint.

**Closed** 2018-10-23 14:50 UTC
Labels: troubleshooting
