### ISSUE TITLE
Hotloading scripts

### ISSUE THREAD

**Issue by Sonicscream** [piqueserver/piqueserver#466] opened 2019-03-17 13:24 UTC
*Is your feature request related to a problem?*
No, it isn't.

*Describe the solution.*
The ability to load scripts in while the server is running.

*Describe alternatives you've considered.*
Restarting after I make a change on a development server.

**Comment by NotAFile** [comment] 2019-03-17 13:53
duplicate of #222

**Closed by NotAFile** 2019-03-17 13:53 UTC
