### ISSUE TITLE
players teleport up to ~10 blocks every second on windows

### ISSUE THREAD

**Issue by pedr69** [piqueserver/piqueserver#559] opened 2019-12-05 10:34 UTC
everyone on the server teleports about 10 blocks(or until they hit a wall) every second or so in the direction of their current movement speed
setting the antispeedhack to 1 block still teleports everyone the same distance and nothing is reported

tried various python versions and results are the same, also tried installing older piqueserver versions but cant install them

win7x64, win10, python 3.7.5, 3.6.8, 3.5.4

**Comment by NotAFile** [comment] 2019-12-05 12:51
We have had other reports of this on windows.

What are your hardware specifications? Do you run the client and server on the same machine? Is this effect reduced when you increase the task priority of piqueserver in the task manager? What is the CPU/GPU usage while this happens?

**Comment by pedr69** [comment] 2019-12-05 13:20
intel 2500k, uhd graphics 3000, client and server are on the same machine but it still happens to other people when only the server is running
setting the priority of piqueserver doesnt change anything
cpu usage 30-50%, gpu usage 50-100% when both the client and server are running
they both drop to pretty much 0% when only the server is running

**Comment by pedr69** [comment] 2019-12-06 13:24
hosting the server on a dell vostro 1015 laptop(core2 duo T6570) pretty much fixes this
it still happens about once every 5 minutes but is not easily reproducable

**Comment by NotAFile** [comment] 2019-12-06 13:50
That's very interesting.

Unfortunately, we don't have the tooling in place to propery debug issues like this right now. What would need to be done is "cpu accounting": checking how much time each phase of the tick cycle takes, and what the culprit for bad performance might be.

**Comment by pedr69** [comment] 2019-12-06 15:24
how do i do that? trying to enter anything into the server console doesnt display what i'm typing and pressing enter causes an error and prevents me from typing further but the server keeps running
i'm guessing this is also unexpected behaviour

i also noticed the openspades client reports from 17-30 ups while playing on the localhosted server
playing on other internet servers it's always ~10

![cmd](https://user-images.githubusercontent.com/18052467/70332629-54553580-1842-11ea-9ce1-f691ae0a9656.png)

**Comment by NotAFile** [comment] 2019-12-06 15:33
Looks like the console might be broken on windows. Can you open a seperate issue for that?

The 17-20 UPS is very concerning. Sounds like some part of the scheduling isn't working. That's a good place start though, thank you for your help.

**Comment by NotAFile** [comment] 2020-04-14 13:11
This might have been fixed by #575. Can anyone using windows try the current master branch?

**Comment by Conticop** [comment] 2020-07-11 15:40
> Can anyone using windows try the current master branch?

Would have tried it many times already, but the given instructions (on Readme) simply doesn't even work for Windows OS. (Only working fine on Linux OS.)
There's no such thing as `source` on the cmd (outside of bash), and in bash it does exist but doesn't work.
![screenshot](https://user-images.githubusercontent.com/58798963/87227706-28cc9780-c39d-11ea-8378-ad44212eb56f.png)

**Comment by Conticop** [comment] 2020-07-16 10:36
After finally resolving some tedious troubles with my Windows machine (no free ports at all...)
I can confirm this issue has been fixed.

**Comment by NotAFile** [comment] 2020-07-26 14:52
Has it also been fixed for grenades and the like? Or just movement.

**Comment by dany-on-demand** [comment] 2021-01-20 22:01
> This might have been fixed by #575. Can anyone using windows try the current master branch?

Can't reproduce on the latest version, at least on LAN

**Comment by NotAFile** [comment] 2021-03-28 18:23
looks like we can close this

**Closed by NotAFile** 2021-03-28 18:23 UTC
Labels: bug, not-our-bug, priority:high
