### ISSUE TITLE
"Incompatible client protocol version"

### ISSUE THREAD

**Issue by PistoletPierre** [piqueserver/piqueserver#188] opened 2017-12-19 00:56 UTC
Not sure if this is a bug or I'm just missing something, but I can't figure out how to get listed on the server list. Furthermore, when attempting to connect manually (via 127.0.0.1 or the aos:// identifier) I immediately get a message saying I was disconnected due to an "Incompatible client protocol version". Screencap below:

<img width="772" alt="screen shot 2017-12-19 at 12 53 31 am" src="https://user-images.githubusercontent.com/6157706/34135220-22969e10-e457-11e7-98b8-0edaa4851561.png">

**Comment by NotAFile** [comment] 2017-12-19 01:45
Hi, what piqueserver version are you using? It appears you are using OpenSpades with 0.75 to connect which should work completely fine...

You need to edit your config.json and set "master: true" to be listed on the server list.

**Comment by PistoletPierre** [comment] 2017-12-19 02:04
A-ha! "master: true" did the trick for getting listed.
A bit of print debugging lead me to see that my client's game version was 3 whereas GAME_VERSION is set to 41 is in constants.py. I don't know where to begin there... should they all be 41?

**Comment by PistoletPierre** [comment] 2017-12-19 02:53
Oops - forgot to mention what version I was using: 0.1.0 (got it from pip)

**Comment by PistoletPierre** [comment] 2017-12-19 02:55
Ohhh that's spooky. In your repo it's also set to 3. What the...? Is that cause for concern?

**Comment by feikname** [comment] 2017-12-19 05:12
Client game = 3 means 0.75, that's our desired behavior. 0.1.0 version from `pip` should work straight out of the box, that's weird.

What distro and what OpenSpades version are you using?

Also, if you can peovide any stacktraces from OpenSpades (launch it from terminal) or piqueserver, that would greatly help in discovering the root cause.

**Comment by feikname** [comment] 2017-12-19 06:04
I get the same with a fresh install from pip here, the error is definitely our fault, my bad.

**Comment by feikname** [comment] 2017-12-19 06:33
Changing `GAME_VERSION` to 3 in `pyspades/constants.py` will solve the issue... But we never changed that line since the project started, and I have no idea why it's different on the `pip` version now all of a sudden (**WTF?!**)

**Comment by feikname** [comment] 2017-12-19 08:36
@PistoletPierre Fixed! Thanks for informing us :+1: 

You can upgrade to the correct version with `pip install --upgrade piqueserver`.

**Comment by feikname** [comment] 2017-12-19 08:37
I will now close this issue as it was solved.

**Closed by feikname** 2017-12-19 08:37 UTC
Labels: bug, distribution

**Comment by NotAFile** [comment] 2017-12-19 08:53
Yes, it seems I accidentally still had some experimental changes in my tree while building the last version of pique... Of course, my client was modified to accept that version, so it worked fine for me while testing...

Anyway, it should work now, Thanks for reporting this!

**Comment by PistoletPierre** [comment] 2017-12-19 12:48
Cheers guys - works like a charm. Now to figure out if I can get my school's firewall to allow the external traffic...

**Comment by NotAFile** [comment] 2017-12-19 13:45
From experience I can say I wish you the best of luck... You will probably need to host the server somewhere else. Note that you don't need any firewall rules to play with people in the same network.
